/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppcastDotxmlRouteImport } from './routes/appcast[.]xml'
import { Route as IndexRouteImport } from './routes/index'

const AppcastDotxmlRoute = AppcastDotxmlRouteImport.update({
  id: '/appcast.xml',
  path: '/appcast.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appcast.xml': typeof AppcastDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appcast.xml': typeof AppcastDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appcast.xml': typeof AppcastDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/appcast.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/appcast.xml'
  id: '__root__' | '/' | '/appcast.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppcastDotxmlRoute: typeof AppcastDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/appcast.xml': {
      id: '/appcast.xml'
      path: '/appcast.xml'
      fullPath: '/appcast.xml'
      preLoaderRoute: typeof AppcastDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppcastDotxmlRoute: AppcastDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
