export const GITHUB_URL = 'https://github.com/limehq/munkel'
export const RELEASES_URL = `${GITHUB_URL}/releases/latest`
export const DOWNLOAD_URL = '/download/latest'
export const PROTOCOL_URL = `${GITHUB_URL}/blob/main/packages/shared-wire/PROTOCOL.md`
export const CLI_URL = `${GITHUB_URL}/tree/main/apps/cli`
export const LICENSE_URL = `${GITHUB_URL}/blob/main/LICENSE`
export const DISCUSSIONS_URL = `${GITHUB_URL}/discussions`
export const SPONSOR_URL = 'https://ko-fi.com/munkel'
export const BREW_CMD = 'brew install limehq/tap/munkel'
